name: prepare-node
description: "THis action prepares the node env"
runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: pnpm install